### ISSUE TITLE
Dropping support for node 8 should not be a minor update

### ISSUE THREAD

**Issue by burdeasa** [szmarczak/defer-to-connect#9]
I don't thinking dropping support for a major version of node (8) should only result in a minor revision update (i.e., from 1.1.0 to 1.1.2). This is causing "npm install" to start failing for our package because apparently some dependent packages use defer-to-connect.

**Comment by szmarczak** [comment]
Oh, wait, you're right.

**Comment by szmarczak** [comment]
Sorry. Released `1.1.3` to fix this. Released also `2.0.0` for Node >=10.
